### ISSUE TITLE
Feature request support for exporting lyrics to ASS/SSA format 

### ISSUE THREAD

**Issue by Tauvic** [X-Raym/REAPER-ReaScripts#12]
Im working on creating karaoke style song movies for my 10 year old daughter to help her practice singing. For that i have a need a script to export the midi lyrics from Reaper to Substation Alpha karaoke format. This format can be edited with Aegisub. Videos can be generated with Handbrake or ffmpeg.  Im thinking on building one myself based on the Ultrastar export script.

**Comment by Tauvic** [comment]
Im looking for a solution to improve a lyrics editing workflow. Imagine you have midi notes for the melody and the lyrics in a file. 
- First organize your lyrics by seperating phrases on seperate lines
- Import lyrics in project notes
- Assign markers to indicate end of each phrase
- Run script to assign lyrics for each phrase to each note in that phrase based on phrase markers
- Have some toolbar to move lyrics within each phrase to the correct note
- Done

**Comment by X-Raym** [comment]
@Tauvic Hi ! I don't use ASS/SSA so I don't plan to add support to it,
feel free to mod my ultrastar script for that ! :)

**Comment by Tauvic** [comment]
Hi, thanx for super fast reply. I understand this request is not in your plan. So i will see if I can do it on my own. Thanks anyway for providing these scripts in the first place. They are a great help for me.
