### ISSUE TITLE
Feature request for advanced workflow and tools for editing lyrics

### ISSUE THREAD

**Issue by Tauvic** [X-Raym/REAPER-ReaScripts#13]
Im working on creating karaoke style song movies for my 10 year old daughter to help her practice singing. Im looking for a solution to improve a lyrics editing workflow. Imagine you have midi notes for the melody and the lyrics in a file. 
- Organize your lyrics by seperating phrases on seperate lines (use a text editor)
- Manually assign markers in Reaper to indicate end of each song phrase
- Manually organize song into regions for verses,  refrain etcetera
- Import lyrics in project notes (or from text file)
- Run script to assign lyrics for each phrase to each note in that phrase based on phrase markers
- please note that not all notes will have lyrics
- Use a custom toolbar to help me move and assign the lyrics within each phrase to the correct note
- Done

Im looking for a toolbar where i can do something like
- Move to next / previous phrase
- Move to a specific note within the phrase (higlight the note so we can get visual feedback)
- Insert empty lyrics (or ~) for notes without lyric text
- Select a specific lyric
- Move this lyric and all the following in this phrase left (or right) one  note
- Play the phrase to verify my lyrics are correct

Im also thinking how to use regions in this workflow.
I now use regios to organize the song in different parts. I would like to work on a part that contains several phrases. Then i might reuse the lyrics assigned in a part and apply the lyrics to another part with slightly different notes and timing.

Im new to Reaper Scripting so this will be hard for me to realise. So some help or suggestions are more than welcome

**Comment by X-Raym** [comment]
@Tauvic Hi !
This is a bit too much I can afford for my free pack, as you have a very clear view of what you need and some code skills, it would be interesting that you dig on your own. There are few ReaScript introduction tutorials on the web ( including my [videos](https://www.youtube.com/watch?v=0Dwonn3Pe2Q) )

You can also surely take advantage of native actions and create custom actions for some of these.

Happy coding !
