### ISSUE TITLE
Bug: X-Raym_Move selected tracks down on visible track list.lua can occasionally nuke folders

### ISSUE THREAD

**Issue by ScottChesworth** [X-Raym/REAPER-ReaScripts#14]
Hi X-Raym,

Just stumbled across a workflow that seems to cause this script to zap a folder from existence. Try this:

1. Create 3 tracks.

2. Name tracks 1-3 "Uno", "Dos" and "Tres" respectively (just seems easier to describe this with track names instead of numbers).

3. Make Uno a folder, and Tres the end of the folder.

4. Select Dos and run "Move selected tracks down on visible track list.lua". The track moves down as expected, and the end of folder is correctly reassigned to Tres, which is now track 2. But...

5. Now select Tres and run "Move selected tracks down on visible track list.lua" again. This time, Tres moves down as expected, but the folder routing disappears entirely.

Thanks in advance if there's anything you can do to tighten this up.

**Comment by X-Raym** [comment]
@ScottChesworth Hi,
Can you make a screen capture of this ?

Thx!

**Comment by X-Raym** [comment]
I think this has been fixed now.
