### ISSUE TITLE
X-Raym_Export markers as YouTube timecode for video description.lua should consider a marker at 00:00

### ISSUE THREAD

**Issue by leafac** [X-Raym/REAPER-ReaScripts#16]
First of all, thanks for this script and **so** many others that I use every day. Also, your writings helped me get started in REAPER 😀

Anyway, on to the issue: https://github.com/X-Raym/REAPER-ReaScripts/blob/068f211311df15266c91b4c3dfdd20e5d3792344/Regions/X-Raym_Export%20markers%20as%20YouTube%20timecode%20for%20video%20description.lua#L21

The [YouTube documentation](https://support.google.com/youtube/answer/9884579?hl=en) says:

> To opt into video chapters, make sure that the first timestamp you list starts with 00:00. Your video should have at least three timestamps listed in ascending order. The minimum length for video chapters is 10 seconds.

So my first marker is at 00:00. But then the action doesn’t include it in the output. This is easy enough to fix by hand on the exported output, of course. But annoying.

Do you think you can fix this? I think it amounts to removing this [`if`](https://github.com/X-Raym/REAPER-ReaScripts/blob/068f211311df15266c91b4c3dfdd20e5d3792344/Regions/X-Raym_Export%20markers%20as%20YouTube%20timecode%20for%20video%20description.lua#L54)…

Alternatively, could you please explain the reasoning behind why the script works this way?

To close, one more time: thanks for everything you do!

**Comment by X-Raym** [comment]
@leafac Thanks for the detailed report, as a quick fix, I've updated the script so that it take care of timecode >= 0 and not just timecode > 0,
I guess in the future it could be updated so that it upload a 00:00 timecode even if none is present in the project, and also a direct copy to clipboard. But I guess it is enough for now 👍 

Cheers !

**Comment by leafac** [comment]
I tested and it works great. Thanks for this 😀

I’m intrigued, though: Could a timecode be negative? REAPER allows extending the timeline to the left? I’ve seen that in Logic, but I don’t know how to do that in REAPER.

**Comment by X-Raym** [comment]
@leafac Yes it can be negative, check project setting project start offset feature.

This allows to have some pre-roll, useful for musical projects which need recording for eg.

**Comment by leafac** [comment]
Oh, cool. I didn’t know about that…
