### ISSUE TITLE
"X-Raym_Export markers and regions as Davinci Resolve EDL file" fails to import with Resolve 17

### ISSUE THREAD

**Issue by Polhemic** [X-Raym/REAPER-ReaScripts#17]
Hi,

It seems that either Davinci Resolve 17 is more particular, or Reaper has changed the output of "reaper.format_timestr_pos( ... , ... , 5).

The generated output contained timecodes of the form "0:00:00:00", however DR 17 silently failed to import them. By making the timecode four groups of two digits (into the form "00:00:00:00") it then accepts the timecodes.

An example of a valid edl marker file follows:
```
TITLE: Wake
FCM: NON-DROP FRAME

1  001      V     C        01:00:00:00 01:00:00:01 01:00:00:00 01:00:00:01  
 |C:ResolveColorGreen |M:Marker 1 |D:1
```

Cheers,
Pol.

**Comment by X-Raym** [comment]
@Polhemic Have you the last version of the script ?
Cause I updated just few days ago to take care of this, it was outputing too much zeros at this time because of REAPER API change.

**Comment by Polhemic** [comment]
Installed via reapack this afternoon - v1.4.2 14th March 2021. Running in reaper v6.12c/x64. I'll update to reaper v6.26, see if that makes a difference.

**Comment by Polhemic** [comment]
Right, updating to reaper 6.26 has fixed it. It's really unfair that reaper changed their API contract.

(Side note: I saw your video about tempo mapping for editing music videos. I'm currently using it to edit multicam footage. Keep up the good work!)

**Comment by X-Raym** [comment]
@Polhemic yeah its pretty rare they change API values but to be fair, my way of handling number of leading zeros for hours was ultra basic.

Glad this script can be helpful to others! Have fun with it!
