### ISSUE TITLE
Viente_X-Raym_BPM Converter.lua decription tag content is wrong

### ISSUE THREAD

**Issue by Buy-One** [X-Raym/REAPER-ReaScripts#18]
Hi

> * Description: Insert FX on selected tracks. FX name is can be edited witing the script code.

https://github.com/X-Raym/REAPER-ReaScripts/blob/master/Items%20Properties/Viente_X-Raym_BPM%20Converter.lua

**Comment by X-Raym** [comment]
@Buy-One thx, fixed soon!
