### ISSUE TITLE
Search and replace in selected tracks names

### ISSUE THREAD

**Issue by JRTaylorMusic** [X-Raym/REAPER-ReaScripts#23]
Line 28
`defaultvals_csv = "0,0,0,0,0,/no"`
adds a 0 to the beginning of selected track names. 
should be, I think:
`defaultvals_csv = "0,0,0,0,/no,/no"`

**Comment by X-Raym** [comment]
@JRTaylorMusic this is the default already:

https://github.com/X-Raym/REAPER-ReaScripts/blob/master/Track%20Properties/X-Raym_Search%20and%20replace%20in%20selected%20tracks%20names.lua#L28
