### ISSUE TITLE
Found an issue with creating seamless loops

### ISSUE THREAD

**Issue by f-conic** [X-Raym/REAPER-ReaScripts#3]
Hey! 

It seems like your script "X-Raym_Create seamless loops from selected items sections inside time selection.lua" doesn't work anymore since the latest Reaper update. 

Whenever I use it I get this error: 
"...s from selected items sections inside time selection.lua:129: attempt to call a nil value (field 'BR_SetItemEdges')"

//S

**Comment by X-Raym** [comment]
@SockPuppet-123 You need to install last sws extension version ! :P
