### ISSUE TITLE
Decrease master playrate by 5 and 10 % makes an increase

### ISSUE THREAD

**Issue by metakeule** [X-Raym/REAPER-ReaScripts#4]
Thanks for your scripts. It looks like 
'Transport/X-Raym_Decrease master playrate by 05%.lua' is a copy of 
'Transport/X-Raym_Increase master playrate by 05%.lua'

'Transport/X-Raym_Decrease master playrate by 10%.lua' is a copy of 
'Transport/X-Raym_Increase master playrate by 10%.lua'

Both do an increase instead of a decrease and also have the wrong 'Undo_EndBlock' message.

**Comment by X-Raym** [comment]
You are right, I'm surprised no one complains about this before. Fixed!

https://github.com/X-Raym/REAPER-ReaScripts/commit/8b25bde8a67134880331fe7cf54abe48e57098ee
